create table if not exists public.tickets (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null,
  category text not null,
  priority text not null check (priority in ('low', 'medium', 'high')),
  status text not null default 'pending' check (status in ('pending', 'in-progress', 'resolved')),
  student_id text not null,
  student_name text not null,
  student_email text not null,
  assigned_to text,
  comments jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists tickets_student_id_idx on public.tickets(student_id);
create index if not exists tickets_status_idx on public.tickets(status);

alter table public.tickets enable row level security;

create policy "Allow read tickets"
on public.tickets
for select
using (true);

create policy "Allow insert tickets"
on public.tickets
for insert
with check (true);

create policy "Allow update tickets"
on public.tickets
for update
using (true)
with check (true);
